Repository mlfiii/Week7Project1, pull requests merged in 2020-02, with the labels that each got.

#11 Corrected the materialize cdn reference.
  index.html
Labels: Front-End

#10 basic getter for headlines plus param handling
  index.html
  newsapi.js
Labels: Back-End

#12 starter page
  .DS_Store
  Images/NewsBackround.jpg
  Images/NewsLayout.jpg
  index.html
  style.css
Labels: Front-End

#13 cleaning up the spacing a bit. indents should be 2 spaces
  index.html
Labels: Front-End

#16 Home page
  .DS_Store
  Images/.DS_Store
  Images/NewsBackround2.jpg
  Images/NewsBackround3.jpg
  index.html
  style.css
Labels: Front-End

#19 Added in favicon into index.html.
  .DS_Store
  Images/news_s.ico
  index.html
Labels: Front-End

#17 Add text analysis
  api.js
  index.html
  newsapi.js
  script.js
Labels: Back-End

#22 Rendering headlines on page.
  index.html
  script.js
  style.css
Labels: Front-End

#21 adding render errors function
  index.html
  script.js
Labels: Front-End

#25 Home page
  .DS_Store
  index.html
  script.js
  style.css
Labels: Front-End, enhancement

#27 save
  Images/Background1.png
  style.css
Labels: Front-End

#30 Rendering headlines
  index.html
  script.js
  style.css
Labels: Back-End, Front-End

#39 new API key
  api.js
Labels: Back-End

#49 adding basic readme
  Images/demo-article-card.png
  Images/demo-main-page.png
  README.md
Labels: Front-End
